### ISSUE TITLE
Cargo build fails on rustc<1.54

### ISSUE THREAD

**Issue by phodina** [zkat/supports-unicode#2]
Hi,

could you please add a note in the README.md to successfuly compile the crate rustc>=1.54 is needed?

The issue is with `#![doc = include_str!("../README.md")]` since the usage of  function-like macros in attributes was not available in the previous versions (unless using nightly).

```
   Compiling libc v0.2.101
   Compiling atty v0.2.14
   Compiling supports-unicode v1.0.2 (/tmp/guix-build-rust-supports-unicode-1.0.2.drv-0/supports-unicode-1.0.2)
error: unexpected token: `include_str`
 --> src/lib.rs:1:10
  |
1 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `supports-unicode`.
```

**Comment by zkat** [comment]
I'll take a PR that inlines the README, if that works for you. I'd rather people be able to use this!

**Comment by zkat** [comment]
MSRV has been documented as 1.70.0.
